
name: Node.js CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: sfc_unit_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: 
          yarn test:unit
      - name: Run integration tests
        env:
          TEST_PG_NAME: sfc_unit_db
          TEST_PG_USER: postgres
          TEST_PG_PASSWORD: password
        run: 
          yarn test:integration
      - name: Check linting
        run: 
          yarn test:unit